"""Source-authored remediation tasks; synthetic premises, no benchmark questions."""


def add_domain(add):
    # Each option tuple is (statement, truth, reason); answer indices are derived.
    add('pick_lines','train','multi_instruction_reconciliation',
        'Use Warehouse & Distribution Science terminology. A completed pick list has three separate instructions executed in order: R, three loose units; S, two cartons; R again, one loose unit. Each loose unit and each carton takes one physical grab. Each instruction causes its own location visit.',
        [('There are three pick-lines.',True,'Each of the three instructions is a line.'),('There are six physical grabs.',True,'3+2+1=6.'),('There are two distinct visited locations.',True,'R and S are two locations, although R is visited twice.'),('There are only two executed location visits.',False,'The execution visits R,S,R, three times.')],
        [('3+2+1','6')], 'Reconcile instruction identity, repeated visits and handling events, rather than one location with renamed quantities.')
    add('pick_lines','train','unequal_area_comparison',
        'Use Warehouse & Distribution Science terminology. Face A displays 18 SKUs in 6 square metres and receives 12 pick-line visits in a shift. Face B displays 24 SKUs in 12 square metres and receives 18 visits. Repeated visits count separately. Compare densities per square metre.',
        [('B has greater SKU density because it holds more SKUs.',False,'18/6=3 exceeds 24/12=2.'),('B has greater pick density because it has more visits.',False,'12/6=2 exceeds 18/12=1.5.'),('A has both greater SKU density and greater observed pick density.',True,'Both ratios are higher for A.'),('The two faces together have SKU density 2.5 per square metre.',False,'Combined density is (18+24)/(6+12)=7/3, not the unweighted mean.')],
        [('18/6','3'),('24/12','2'),('12/6','2'),('18/12','3/2'),('(18+24)/(6+12)','7/3')], 'Compare unequal denominators and reject the unweighted aggregation shortcut.')
    add('pick_lines','train','partial_grab_identifiability',
        'Use Warehouse & Distribution Science terminology. A log confirms that 14 separate picking instructions were completed, each at one location. Across the list there are five distinct locations. Each instruction required between one and four physical grabs, but quantities and grab counts were lost.',
        [('The log establishes 14 completed pick-lines.',True,'Completed instruction count is known.'),('At least 14 physical grabs occurred.',True,'Every completed instruction required at least one grab.'),('Exactly 14 physical grabs occurred.',False,'Some instructions could require two to four grabs.'),('The five distinct locations imply only five pick-lines.',False,'Multiple instructions can visit the same location.')],
        [('14*1','14'),('14*4','56')], 'Identify bounds rather than invent a precise event count from incomplete records.')
    add('pick_lines','train','layout_change_with_fixed_activity',
        'Use Warehouse & Distribution Science terminology. Six popular SKUs are moved from a three-square-metre pick face to a two-square-metre face. The same 24 pick-line visits occur in each observed shift. The rest of the layout and actual walking distances are not recorded.',
        [('SKU density of this face rises from two to three per square metre.',True,'6/3=2 and 6/2=3.'),('Observed pick density rises from eight to twelve per square metre.',True,'24/3=8 and 24/2=12.'),('The observed visit count itself has not increased.',True,'Both shifts have 24 visits.'),('These records do not determine the exact change in total walking distance.',True,'The source gives tendencies; the complete route and distances are absent.')],
        [('6/3','2'),('6/2','3'),('24/3','8'),('24/2','12')], 'Separate changes in the denominator from activity and avoid an exact travel claim.')
    add('pick_lines','dev','order_merge_and_separate',
        'Use Warehouse & Distribution Science terminology. Order U needs one unit from each of bins A,B,C; order V needs one from B,C,D. A WMS co-picking rule merges requests into one instruction per visited bin, then separates items into orders downstream. Each unit requires one grab; bins hold distinct SKUs. Compare merged execution with executing both orders separately.',
        [('Merged execution uses four pick-lines and six grabs.',True,'Four bin instructions still retrieve six units.'),('Merging removes the need to separate the two orders.',False,'Downstream separation remains explicitly required.'),('Merging reduces instruction visits by four.',False,'Six separate visits become four, a reduction of two.'),('Six physical grabs force six merged pick-lines.',False,'B and C each require multiple grabs under one merged instruction.')],
        [('3+3','6'),('6-4','2')], 'Held-out construction: coalesce two order graphs and preserve downstream separation, not a rescaled single instruction.')
    add('pick_lines','dev','recover_instruction_count_from_events',
        'Use Warehouse & Distribution Science terminology. A scanner recorded 30 unit-grab events on a known ten-square-metre pick face. Every completed instruction produced at least one event, and no event belongs to two instructions. Instruction IDs were lost. The analyst needs completed pick-lines per square metre. Which additions would be sufficient?',
        [('Restore a stable unique instruction ID on every event, then count distinct IDs.',True,'The stated completeness makes distinct IDs equal completed lines.'),('Obtain only the total number of retrieved units.',False,'Units or grabs do not determine how many instructions they belong to.'),('Recover a reliable total count of completed instructions, including repeat visits.',True,'This supplies the needed numerator directly.'),('Recover a complete register containing exactly one row for each completed instruction.',True,'Its row count supplies the numerator; area is already known.')],
        [], 'Held-out construction: choose sufficient recovery evidence for a lost grouping key; no claim of an independent source domain.')

    add('batch_tradeoff','train','duplicate_cost_ledger',
        'Apply the Warehouse & Distribution Science batching trade-off. Separate picking costs 80 units of walking. Batching costs 30 walking, 12 separation and 8 additional space. These are all costs. A report repeats the same separation invoice, with the same invoice ID, in a second handling-cost row.',
        [('The correctly deduplicated batch costs 50.',True,'30+12+8=50.'),('The net saving relative to separate picking is 30.',True,'80-50=30.'),('The repeated invoice makes the true batch cost 62.',False,'It is the same expense, not additional work.'),('Ignoring space would leave the numerical saving unchanged.',False,'Ignoring eight units changes the saving from 30 to 38.')],
        [('30+12+8','50'),('80-(30+12+8)','30')], 'Reconcile invoice identity and the incremental cost boundary before comparing actions.')
    add('batch_tradeoff','train','cost_with_space_feasibility',
        'Apply the Warehouse & Distribution Science batching trade-off. Only four square metres of staging space are available. Plan A avoids 36 cost units of walking, adds 16 separation and 9 space cost, but needs five square metres. Plan B avoids 30, adds 17 separation and 5 space cost, and needs four square metres. Separate picking is feasible with zero incremental saving. Minimize total cost among feasible plans.',
        [('A is the best feasible plan because it saves 11.',False,'Its five-square-metre requirement is infeasible.'),('B is the best feasible plan and saves 8.',True,'30-17-5=8, with a feasible footprint.'),('B raises cost by 8 relative to separate picking.',False,'Its incremental saving is positive eight.'),('Separate picking is cheapest among feasible plans.',False,'B is feasible and cheaper by eight.')],
        [('36-16-9','11'),('30-17-5','8')], 'Conjoin physical feasibility with complete cost accounting.')
    add('batch_tradeoff','train','strict_break_even_boundary',
        'Apply the Warehouse & Distribution Science batching trade-off. A feasible batch avoids 40 units of walking cost, adds 25 separation and 15 space cost. These are the only changes. Consider strict cost reduction and small one-unit changes with feasibility held fixed.',
        [('The original batch breaks even.',True,'40-25-15=0.'),('The original batch is strictly cheaper.',False,'Equality is not strict reduction.'),('Increasing space cost by one makes batching cost one more.',True,'25+16-40=1.'),('Reducing separation cost by one makes batching save one.',True,'40-24-15=1.')],
        [('40-25-15','0'),('25+16-40','1'),('40-24-15','1')], 'Audit strict and non-strict claims at a break-even boundary.')
    add('batch_tradeoff','train','exclusive_interventions_with_fees',
        'Apply the Warehouse & Distribution Science batching trade-off. A batch avoids 55 cost units of walking but adds 60 in separation and space. At most one intervention is allowed. I reduces separation by 8 and charges a 2-unit fee. J reduces space by 10 and charges a 3-unit fee. All actions are feasible and have no other effects. Minimize total cost.',
        [('Without intervention batching costs five more than separate picking.',True,'60-55=5.'),('I makes batching save one net cost unit.',True,'55-(60-8+2)=1.'),('J makes batching save two net cost units.',True,'55-(60-10+3)=2.'),('J is the cheaper of the two allowed interventions.',True,'Its net saving is two versus one.')],
        [('60-55','5'),('55-(60-8+2)','1'),('55-(60-10+3)','2')], 'Intervention fees and mutually exclusive cost minimization add premises absent from the old intervention diagnostic.')
    add('batch_tradeoff','dev','robust_cost_ranges',
        'Apply the Warehouse & Distribution Science batching trade-off. Walking avoided is 30 cost units. Separation may be any value from 12 to 20 and space from 7 to 14; all combinations are possible. A contract may cap these components and charge a fee. All scenarios are feasible. Assess strict savings, including the fee.',
        [('Some original cost combinations make batching cheaper.',True,'12+7=19 is below 30.'),('Every original combination makes batching cheaper.',False,'20+14=34 exceeds 30.'),('Caps of 18 and 8 with fee 2 guarantee a strict saving.',True,'The worst permitted total is 28, below 30.'),('Caps of 20 and 8 with fee 2 guarantee a strict saving.',False,'Worst total 30 only breaks even.')],
        [('12+7','19'),('20+14','34'),('18+8+2','28'),('20+8+2','30')], 'Held-out construction: existential versus universal guarantees over joint cost ranges.')
    add('batch_tradeoff','dev','shared_setup_across_waves',
        'Apply the Warehouse & Distribution Science batching trade-off. Two order waves can be batched separately or together. Each batched wave avoids 25 walking-cost units and adds 12 variable separation/space cost. A common setup costs 22 once if either or both waves are batched, never twice. All choices are feasible and independent except for that shared setup.',
        [('Batching only one wave reduces total cost.',False,'25-12-22=-9.'),('Batching both waves saves four cost units in total.',True,'50-24-22=4.'),('Batching both requires 44 units of setup cost.',False,'Setup is shared and paid once.'),('Rejecting each wave based only on its isolated cost can miss the joint saving.',True,'Each isolated choice loses nine; the joint choice saves four.')],
        [('25-12-22','-9'),('2*25-2*12-22','4')], 'Held-out construction: non-additive shared setup and joint decisions across waves.')

    add('serial_parallel','train','release_time_interaction',
        'Use Warehouse & Distribution Science picking concepts. Pick A takes 6 minutes and is available at 0. Pick B takes 4 minutes and is unavailable before 5. Serial: one worker does A then B and loads for 1 minute. Parallel: separate workers start each pick as soon as available, then one worker consolidates for 2 and loads for 1. Count active labor only.',
        [('Serial loading finishes at minute 11.',True,'A ends 6, B ends 10, loading ends 11.'),('Parallel loading finishes at minute 12.',True,'B ends 9, then 2+1.'),('Parallel uses 13 active person-minutes.',True,'6+4+2+1=13.'),('Parallel is faster in this scenario.',False,'Twelve is later than eleven.')],
        [('6+4+1','11'),('5+4+2+1','12'),('6+4+2+1','13')], 'A release-time constraint can reverse a simultaneous-start intuition.')
    add('serial_parallel','train','deadline_and_labor_budget',
        'Use Warehouse & Distribution Science picking concepts. Three feasible process designs start at 0. S uses one worker for picks of 10 and 6 minutes, then loads for 1. P uses two concurrent picks of 10 and 6, then consolidation 4 and loading 1. R uses two concurrent picks of 8 and 6, then consolidation 3 and loading 1. Each listed task uses one worker and all labor is included. The loading deadline is 16 and active-labor budget 20.',
        [('P meets both constraints.',False,'It finishes 15 but uses 21 person-minutes, exceeding 20.'),('S meets the loading deadline.',False,'S finishes 17.'),('R meets both constraints.',True,'R finishes 12 and uses 18 person-minutes.'),('S requires 21 active person-minutes.',False,'Its active work is 17.')],
        [('10+6+1','17'),('10+4+1','15'),('10+6+4+1','21'),('8+3+1','12'),('8+6+3+1','18')], 'Conjoin a deadline and a binding labor budget: S fails time, P fails work, R meets both.')
    add('serial_parallel','train','bottleneck_perturbation',
        'Use Warehouse & Distribution Science picking concepts. Concurrent picks A and B start at 0 and take 11 and 7 minutes. After both finish, consolidation takes 3 and loading 1. Option X shortens only B to 3 minutes; option Y shortens only A to 8. All other timings are fixed.',
        [('X leaves completion time at 15 minutes.',True,'A remains the 11-minute bottleneck.'),('Y reduces completion time by three minutes.',True,'Completion changes from 15 to 12.'),('X reduces completion time by four minutes.',False,'Shortening a non-bottleneck here does not shorten elapsed completion.'),('Y reduces completion time by six minutes.',False,'The reduction is only three.')],
        [('11+3+1','15'),('8+3+1','12'),('15-12','3')], 'Identify which perturbation changes the bottleneck, not just total work.')
    add('serial_parallel','train','precedence_graph_report',
        'Use Warehouse & Distribution Science picking concepts. A takes 6 minutes. B takes 4 and cannot begin before A finishes. C takes 8 and starts with A at 0 on another worker. Consolidation takes 2 after all picks, then loading 1. A report predicts completion at 11 by treating all three picks as simultaneous. Workers are otherwise available; count active work only.',
        [('B finishes at minute 10.',True,'B starts after A at 6 and runs four minutes.'),('Loading actually finishes at minute 13.',True,'Last pick finishes 10; consolidation and loading add three.'),('Total active work is 21 person-minutes.',True,'6+4+8+2+1=21.'),('The report ignores the A-before-B dependency.',True,'That dependency prevents simultaneous starts of A and B.')],
        [('6+4','10'),('6+4+2+1','13'),('6+4+8+2+1','21')], 'Audit a precedence graph; the old pilot had only two independent picks.')
    add('serial_parallel','dev','inverse_release_bound',
        'Use Warehouse & Distribution Science picking concepts. A starts at 0 and lasts 8 minutes. B lasts 5 and starts at its nonnegative release time r on another worker. Consolidation takes 3 after both finish, then loading 2. No other work or delay occurs. Loading must finish by 17.',
        [('A release time r=6 permits on-time loading.',True,'B ends 11 and loading ends 16.'),('A release time r=8 misses the deadline.',True,'B ends 13 and loading ends 18.'),('The latest permitted release time is 7.',True,'B must finish by 12;7+5=12.'),('Release time can change completion while active person-work stays 18.',True,'The work durations stay fixed; release time changes waiting.')],
        [('6+5+3+2','16'),('8+5+3+2','18'),('17-3-2-5','7'),('8+5+3+2','18')], 'Held-out construction: infer a latest release bound, rather than forward-score known schedules.')
    add('serial_parallel','dev','interrupted_consolidation',
        'Use Warehouse & Distribution Science flow-time concepts. Two picks start at 0 and finish at 6 and 10. One worker must then perform 4 minutes of consolidation and 2 of loading. That worker is unavailable from 11 until 14. Consolidation may either pause/resume or, under another policy, must run uninterrupted. Loading follows consolidation. There is no other delay. Deadline:19.',
        [('Pause/resume consolidation can meet the deadline.',True,'One minute at 10, three at 14, then loading 17 to 19.'),('Uninterrupted consolidation can meet the deadline.',False,'Earliest interval 14 to 18, loading ends 20.'),('Active work totals 22 person-minutes under either policy.',True,'6+10+4+2=22; unavailability is not active labor.'),('Under the earliest uninterrupted schedule, loading ends at 20.',True,'Consolidation 14 to 18 followed by two minutes loading.')],
        [('14+3+2','19'),('14+4+2','20'),('6+10+4+2','22')], 'Held-out construction: preemption, unavailability and active-work versus wall-clock time.')

    add('transport_capacity','train','cancellation_vs_rejection',
        'Use the archived transport-supply discussion. Two departures have capacities 6 and 8. Initial requests are 9 and 4. Three first-departure requests cancel before allocation; no others change. Each departure carries all remaining eligible requests up to capacity, with no transfer between departures. Distinguish cancellation from a capacity rejection.',
        [('Total realized carriage is 10.',True,'The remaining requests are 6 and 4.'),('There are no capacity-rejected requests.',True,'Both remaining demands fit.'),('The three cancellations must not be recorded as capacity rejections.',True,'They are withdrawn before allocation.'),('Six spaces go unused.',False,'Capacity 14 minus carriage 10 leaves four.')],
        [('9-3+4','10'),('6+8-10','4')], 'Reconcile time-varying requests and distinguish withdrawal from unmet eligible demand.')
    add('transport_capacity','train','limited_flexible_requests',
        'Use the archived transport-supply discussion. Morning and evening departures each carry at most 8 units. Eleven units request morning and three request evening. Exactly two morning units may shift to evening; all others require their original departure. Every eligible unit fits identically and no other service is available. Maximize served units.',
        [('All 14 units can be served because daily capacity is 16.',False,'Even after shifting two, nine units still require morning capacity eight.'),('The maximum served is 13 after shifting both flexible units.',True,'Morning 8 plus evening 5.'),('The optimal allocation leaves no evening space unused.',False,'Evening uses five of eight spaces.'),('All 11 morning-request units travel in the morning.',False,'Morning capacity is only eight.')],
        [('11-2','9'),('8+3+2','13'),('8-5','3')], 'Solve eligibility-limited reassignment rather than unconstrained daily aggregation.')
    add('transport_capacity','train','partial_record_necessity',
        'Use the archived transport-supply discussion. Two departures each have capacity 10 and carry every eligible request up to that capacity. No cancellations, transfers or other restrictions apply. The day carried 16 units in total; the first departure carried 8. Determine what necessarily follows.',
        [('The second departure carried 8.',True,'16-8=8.'),('Neither departure rejected requests for lack of capacity.',True,'Each carried fewer than 10 under the stated carry-up-to-capacity rule.'),('The first departure could have had 12 eligible requests.',False,'It would have carried 10, contradicting the recorded eight.'),('The day realized 20 units of carriage.',False,'Observed carriage is 16, not total capacity 20.')],
        [('16-8','8'),('10-8','2')], 'Use a partial record and an explicit work-conserving rule to infer necessity, not just possibility.')
    add('transport_capacity','train','capacity_action_feasibility',
        'Use the archived transport-supply discussion. Morning/evening demands are 12/4 and capacities 8/8. Demand cannot shift. Choose at most one action: move four evening spaces to morning for cost 3; buy four extra morning spaces for cost 6; or move five evening spaces to morning for cost 2. No other changes occur. The objective is to serve every request at minimum added cost.',
        [('Moving four spaces serves every request.',True,'Capacities become 12/4.'),('Buying four morning spaces also serves all requests but costs more.',True,'Capacities 12/8 fit, at cost 6 versus 3.'),('Moving five spaces leaves one evening request unserved.',True,'Evening capacity becomes 3 against demand 4.'),('Moving four spaces is the cheapest feasible action for the objective.',True,'The cheaper move-five action fails the evening constraint.')],
        [('8+4','12'),('8-4','4'),('8-5','3')], 'Conjoin two service constraints before ranking capacity investments by cost.')
    add('transport_capacity','dev','connection_path_capacity',
        'Use the archived transport-supply discussion. Five units need same-day delivery. A two-leg path has capacity 6 on each leg: the first departs at 10 and arrives at 13; the second departs at 12 and arrives at 16. Transfer is possible only after first-leg arrival. A direct service departing at 11 and arriving at 15 has capacity 2. All units are ready at 9. There are no other services or overnight same-day options.',
        [('At most two units can arrive the same day under this schedule.',True,'Only the direct service is temporally feasible.'),('Six spaces on each connection leg guarantee delivery of all five.',False,'The first leg misses the second departure.'),('Increasing only first-leg capacity to 20 would enable the connection.',False,'More spaces do not repair the missed departure.'),('Unused spaces on the departed second leg can be stored as that same service for tomorrow.',False,'A departed service cannot be stored.')],
        [], 'Held-out construction: temporal path feasibility across legs, rather than one-period totals.')
    add('transport_capacity','dev','capacity_uncertainty_guarantee',
        'Use the archived transport-supply discussion. Departure A has unknown integer capacity between 4 and 7; B has capacity 8. Requests are 9 for A and 3 for B. Exactly two A requests can be reassigned to B; the others cannot shift. Reassign both, then carry as many eligible requests as possible. Assess what is guaranteed versus merely possible.',
        [('At least nine units are guaranteed to be served.',True,'Worst case A serves 4 and B serves 5.'),('If A capacity is 4, only nine units can be served.',True,'A serves four and B five.'),('Serving all 12 is possible if A capacity is 7.',True,'A serves 7 and B serves 5.'),('B has three unused spaces after the reassignment.',True,'B receives five against capacity eight.')],
        [('4+3+2','9'),('7+3+2','12'),('8-3-2','3')], 'Held-out construction: worst-case guarantees under uncertain capacity and eligibility constraints.')
