"""Broader knowledge checks, with source-separated and shared-group strata explicit."""


def add_retention(add):
    def keep(unit,design,q,options,checks=()):
        add(unit,'retention',design,q,options,list(checks),
            'Retention only: apply archived source scope to this new scenario; do not use for training.')
    keep('pest','external_vs_internal',
        'Use the general PEST framework. A firm lists national inflation, population ageing, new industrial robotics technology and its own weekly picker roster. Identify justified classifications for an external macro-environment review.',
        [('National inflation is an economic factor.',True,'It concerns the external economic environment.'),('Population ageing is a social factor.',True,'It is an external demographic trend.'),('The internal picker roster is itself an external macro factor.',False,'It is an internal operating arrangement.'),('Industrial robotics developments can be a technological factor.',True,'They concern the technological environment.')])
    keep('pest','review_scope_repair',
        'Use the general PEST framework. A proposed macro-environment review covers only internal warehouse staffing and omits external political and technological changes. Which corrections belong in the review?',
        [('Assess changes in national trade policy.',True,'Political macro-environment is within PEST.'),('Treat an internal shift swap as a national political change.',False,'That event is internal operations.'),('Assess external developments in automation technology.',True,'Technological macro-environment is in scope.'),('Drop all external economic conditions because the firm has a budget.',False,'An internal budget does not remove external economic factors.')])
    keep('abc','control_class_consistency',
        'Use the archived ABC inventory-control definitions. Item groups are already classified A,B,C; no reclassification is requested. A proposal assigns very tight controls and accurate records to A, moderate controls and records to B, and the simplest controls and minimal records to C.',
        [('The proposed A controls match the cited definition.',True,'A requires very tight control and accurate records.'),('The proposed B controls match the cited definition.',True,'B is less tightly controlled with moderate records.'),('The proposed C controls match the cited definition.',True,'C uses the simplest controls and minimal records.'),('The definition requires all three groups to use identical control intensity.',False,'It expressly differentiates the groups.')])
    keep('abc','prioritize_control_repair',
        'Use the archived ABC inventory-control definitions. A items currently have loose controls and unreliable records. B items have moderate controls and records. C items have simple controls and minimal records. One action can be taken to correct the demonstrated mismatch, without changing class assignments.',
        [('Strengthen A controls and restore accurate A records.',True,'A is the stated mismatch to its required control level.'),('Reduce A records to the C standard.',False,'That moves A away from its definition.'),('Require C to have tighter control than A merely because its letter is later.',False,'Alphabet order does not imply tighter control.'),('Remove moderate B records to correct the A defect.',False,'That does not correct A and undermines the B standard.')])
    keep('reorder','error_vs_variability',
        'Use the archived MITx continuous-review (s,Q) formulation. Expected lead-time demand is 40. Forecast-error RMSE over lead time is zero, even though observed demand varies. The safety factor is positive. No approximation replacing forecast error with demand variability is authorized.',
        [('The stated formula gives reorder point 40.',True,'Expected demand plus safety factor times zero is 40.'),('Positive observed demand variability alone requires a positive error-based safety term here.',False,'The formula uses the specified zero forecast-error RMSE.'),('Substituting demand standard deviation would introduce an additional approximation.',True,'The source distinguishes the two measures.'),('Forecast error and demand variability must be identical by definition.',False,'The source explicitly rejects that identity.')], [('40+3*0','40')])
    keep('reorder','strict_trigger_scope',
        'Use the archived MITx (s,Q) policy exactly as stated in the source: apply its inventory-position trigger. Reorder point s is 50 and order quantity Q is 12. Compare observations with inventory position exactly 50 and then 49; all other conditions are unchanged.',
        [('At position 49 the policy triggers an order of 12.',True,'Position is below s and quantity is Q.'),('Position exactly 50 is below the reorder point.',False,'Equality is not below.'),('Changing the trigger observation from 50 to 49 changes whether the stated trigger is satisfied.',True,'The source uses falls below s.'),('The policy orders 49 units because current position is 49.',False,'Order quantity is Q=12, not current position.')])
    keep('rail_transfer','direct_vs_other_mode',
        'Use the 2019 Eurostat/UNECE/ITF railway loaded/unloaded definitions. Shipment A transfers directly between two railway vehicles. Shipment B is unloaded from rail onto a road vehicle and later loaded onto another railway vehicle. Classify these intermediate operations.',
        [('A counts as an intermediate rail unloading followed by loading.',False,'Direct rail-to-rail transfer is excluded.'),('B counts as unloading from the first rail vehicle and loading on the second.',True,'An intervening other mode satisfies the cited distinction.'),('Changing only a tractive vehicle also counts as cargo unloading/loading.',False,'The source explicitly excludes a tractive-vehicle change.'),('The same railway exception automatically governs every road transfer.',False,'The source distinguishes rail from road and inland waterway rules.')])
    keep('rail_transfer','event_sequence_audit',
        'Use the 2019 Eurostat/UNECE/ITF railway loaded/unloaded definitions. Between the initial origin loading and final unloading, one consignment has three events: locomotive replacement, direct wagon-to-wagon transfer, then transfer through a road vehicle before entering a new wagon. Count only qualifying intermediate rail operations.',
        [('There is one qualifying intermediate rail unloading.',True,'Only the transfer through the road vehicle qualifies.'),('There is one qualifying intermediate rail loading.',True,'The subsequent rail entry after the road stage qualifies.'),('All three events each add a rail loading.',False,'The first two are explicitly excluded.'),('Removing the road stage would leave only excluded events in this list.',True,'Locomotive and direct rail transfers remain.')])
    keep('postponement','preserve_allocation_flexibility',
        'Use the archived two-stage delayed-differentiation model. A common semi-finished item can later become either product A or B. Final demand is not yet known. Customizing all common stock to A now would make conversion to B impossible. The current generic stock has not yet been assigned to either end product.',
        [('Keeping generic stock preserves allocation flexibility between A and B.',True,'Differentiation has not yet committed it to one end product.'),('Customizing everything to A preserves the same flexibility to B.',False,'The scenario explicitly removes conversion to B.'),('Postponement guarantees every future demand can be served regardless of lead time.',False,'The source makes benefits conditional on demand and lead times.'),('Merely waiting to combine truck loads is the same product-differentiation operation.',False,'The source distinguishes shipment delay from product differentiation.')])
    keep('postponement','customization_deadline_limit',
        'Use the archived delayed-differentiation model. Generic stock is ready now. Customization requires two full days, then delivery one further day. A new order requires delivery within two days. These stages are sequential and cannot be shortened. Assess the claim that postponement by itself guarantees service.',
        [('This order cannot meet the given deadline through that sequence.',True,'Two plus one is three days, exceeding two.'),('Generic stock alone guarantees on-time service here.',False,'The remaining stages exceed the deadline.'),('The example illustrates the source warning that production lead times affect benefits.',True,'Flexibility does not eliminate stage duration.'),('Waiting longer before customization necessarily fixes the deadline problem.',False,'Waiting only leaves less time.')], [('2+1','3')])
    keep('contracts','contract_and_container_dimensions',
        'Use Rodrigue and Slack\'s cited terminology, not an unspecified statistical vocabulary. A container travels by rail and then road under one through contract. Its contents are not separately handled at the mode change.',
        [('The integrated one-contract journey fits the cited multimodal terminology.',True,'The named vocabulary defines contract integration this way.'),('Unchanged container handling alone would establish the contract arrangement if the contract fact were missing.',False,'Physical unit handling and contracts are different dimensions.'),('The unchanged unit can facilitate the mode connection without handling each item.',True,'This is the cited physical role of a transferable load unit.'),('The journey is transmodal because two different modes are used.',False,'Transmodal connects services within the same mode.')])
    keep('contracts','same_mode_multiple_carriers',
        'Use Rodrigue and Slack\'s cited terminology. Goods move between two rail services operated by different carriers. The mode remains rail throughout. Carrier and contract changes are recorded, but no truck, ship or aircraft leg occurs.',
        [('Connecting these services within one mode fits transmodal movement.',True,'The relevant condition is same mode.'),('Two carrier names alone prove a sequence of different modes.',False,'Carrier identity is not transport mode.'),('Calling the transfer rail-to-road is supported by these records.',False,'No road leg occurs.'),('A contract change necessarily means individual items were unpacked.',False,'Contracts do not establish physical handling.')])

    keep('warehouse_roles','mixed_wip_and_fulfillment',
        'Use the MITx warehouse-function distinctions. One facility holds partly assembled components awaiting production and also has a separate operation shipping small online orders directly to individual consumers. Classify functions expressly demonstrated; do not assume every facility has only one role.',
        [('The component operation demonstrates a WIP warehouse function.',True,'Partly completed assemblies are WIP.'),('The consumer-order operation demonstrates a fulfillment-center function.',True,'It sends small orders to individual consumers.'),('The WIP function rules out every fulfillment function at the same facility.',False,'The source distinctions do not impose mutually exclusive facilities.'),('The facts establish that every stored item is a raw material.',False,'Some are partly assembled and the other stream fulfills orders.')])
    keep('warehouse_roles','location_and_inventory_roles',
        'Use the MITx warehouse-function distinctions. Site A stores raw material beside a production source. Site B is in the field near customers and holds stock to respond rapidly to them. Only these operations are specified; classify the demonstrated functions.',
        [('A demonstrates raw-material storage near a source.',True,'Both material state and source proximity are specified.'),('B demonstrates a local-warehouse function.',True,'It is near customers for rapid response.'),('A must be a WIP operation because it is near production.',False,'Raw material is specified, not partial assemblies.'),('B must cross-dock mixed pallets from multiple suppliers.',False,'Those mixing-center facts are not supplied.')])
    keep('shipping_controls','stage_event_mapping',
        'Use the MITx Check, Pack & Ship distinctions. Event A verifies labels, weight and cube. Event B adds damage protection and unitizes pallets. Event C allocates dock doors and optimizes trailer loading. Evaluate this activity classification.',
        [('A belongs to Checking.',True,'Label and weight/cube verification is Checking.'),('B belongs to Packing.',True,'Protection and unitizing are Packing.'),('C belongs to Shipping.',True,'Dock and loading optimization are Shipping activities.'),('C is label verification merely because the shipment has a label.',False,'The stated C actions are different.')])
    keep('shipping_controls','fix_the_demonstrated_defect',
        'Use the MITx Check, Pack & Ship distinctions. Protective packing and pallet unitizing are complete. A later inspection finds that a shipping label names the wrong destination; weight and cube have not been verified. No other defect is given.',
        [('Correcting and verifying the label addresses a Checking activity.',True,'Checking includes creating and verifying labels.'),('Completing weight and cube verification addresses Checking.',True,'Both are included in that function.'),('A better trailer-loading plan alone corrects the wrong label text.',False,'Loading optimization does not fix the identified label content.'),('The evidence proves every pallet must be unitized again.',False,'Packing is already complete and no packing defect is stated.')])
    keep('outsourcing','responsibility_after_contract',
        'Use the cited health-commodity logistics handbook outsourcing discussion. A health organization contracts its warehousing operation to a 3PL. Its director proposes closing all internal contract-management and KPI-monitoring responsibilities solely because execution is now outsourced.',
        [('The organization still needs supply-chain management involvement.',True,'Outsourcing does not remove management responsibility.'),('Monitoring warehouse KPIs remains relevant.',True,'The source expressly requires KPI monitoring.'),('Contract-management skills remain relevant.',True,'Managing external implementation requires these skills.'),('The outsourcing contract by itself proves every logistics concern has been solved.',False,'The source rejects outsourcing as an automatic cure.')])
    keep('outsourcing','provider_quality_and_governance',
        'Use the cited health-commodity logistics handbook outsourcing discussion. A low-price provider is available, but its reliability has not been assessed. The organization also lacks staff with contract-management skills. No further evidence about quality or total cost is supplied.',
        [('Assessing provider reliability addresses a named initial issue.',True,'Availability and reliability of quality options matter.'),('Developing contract-management capability addresses a named requirement.',True,'The organization must possess or develop this skill.'),('A low quote alone guarantees successful outsourcing.',False,'Quality and management capability remain unresolved.'),('The organization can remove KPI monitoring to offset the quote.',False,'Constant involvement and KPI monitoring remain required.')])
    keep('holding_cost','duplicate_holding_component',
        'Use the MITx inventory carrying-cost boundaries. A defined period has capital opportunity cost 30, storage expense 40 and inventory-risk cost 10. The same storage invoice is also listed as a separate 40-unit cost below the holding-cost subtotal. There are no other costs. Audit a total that includes both rows.',
        [('The nonduplicated total is 80.',True,'30+40+10=80.'),('Counting the storage invoice in both places yields a justified total 120.',False,'That counts the same expense twice.'),('Storage can be an operating component of holding cost.',True,'The source includes relevant warehouse operating expenses.'),('The source requires a universal 25 percent carrying rate for every item.',False,'A fixed rate is a scenario assumption, not a universal identity.')], [('30+40+10','80'),('80+40','120')])
    keep('holding_cost','allocated_vs_incremental_boundary',
        'Use the MITx inventory carrying-cost boundary guidance. For a small inventory change, incremental capital and risk costs are 10 and 3. Existing rent does not change. A separate full-allocation report assigns 20 of existing rent to this stock. No other costs occur. Keep the two reports\' stated boundaries distinct.',
        [('The incremental report totals 13.',True,'Only changed costs 10+3 are included.'),('The full-allocation report totals 33.',True,'It additionally assigns 20 rent.'),('The 20 difference reflects the explicitly different costing boundaries.',True,'The full report allocates an unchanged expense.'),('These figures do not establish one universal carrying-cost percentage.',True,'No universal rate follows from one specified costing example.')], [('10+3','13'),('10+3+20','33')])
